# Conditional AE Hyperparameter Experiments (src-only)

Notebook for running sweeps directly via `src/*` modules (no dependency on `scripts/`).

Per-run artifacts are logged to `experiments/cae/<run_name>/`:
- `config.json`
- `metrics.json`
- `history.csv`
- `checkpoints/cae_best.pt`
- TensorBoard logs in `tb/`

In [1]:
from __future__ import annotations

import json
import os
import random
import sys
from dataclasses import asdict
from datetime import datetime
from itertools import product
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch
from IPython.display import display

from typing import Any


def find_project_root(start: Path) -> Path:
    start = start.resolve()
    for candidate in [start, *start.parents]:
        if (candidate / 'src').is_dir():
            return candidate
    raise FileNotFoundError('Could not find project root containing src/.')


PROJECT_ROOT = find_project_root(Path.cwd())
os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.eval import EvalConfig, evaluate_model
from src.model import ConditionalAE, ModelConfig, count_trainable_parameters
from src.train import SummaryWriter, TrainConfig, build_dataloaders, train_model
from src.utils import (
    get_device,
    load_metadata,
    resolve_urbansound_data_dir,
    save_log_mel_spectrogram,
    unpack_audio,
)

print('PROJECT_ROOT:', PROJECT_ROOT)

PROJECT_ROOT: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project

In [2]:
# Paths
DATA_DIR = resolve_urbansound_data_dir("/mnt/shared/gen_ai_proj_data/UrbanSound8K/")
AUDIO_DIR = DATA_DIR / 'audio'
AUDIO_UNPACKED_DIR = DATA_DIR / 'audio_unpacked'
SPEC_ROOT = DATA_DIR / 'spectrograms'
EXPERIMENTS_DIR = PROJECT_ROOT / 'experiments' / 'cae'
EXPERIMENTS_DIR.mkdir(parents=True, exist_ok=True)

device = get_device()
metadata = load_metadata(DATA_DIR)

print('DATA_DIR:', DATA_DIR)
print('AUDIO_UNPACKED_DIR:', AUDIO_UNPACKED_DIR)
print('SPEC_ROOT:', SPEC_ROOT)
print('EXPERIMENTS_DIR:', EXPERIMENTS_DIR)
print('Device:', device)
print('Metadata rows:', len(metadata))

DATA_DIR: /mnt/shared/gen_ai_proj_data/UrbanSound8K
AUDIO_UNPACKED_DIR: /mnt/shared/gen_ai_proj_data/UrbanSound8K/audio_unpacked
SPEC_ROOT: /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
EXPERIMENTS_DIR: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cae
Device: cuda
Metadata rows: 8732

In [3]:
# Sweep config (edit for your experiments)
LATENT_DIMS = [64, 128, 256]
EMBED_DIMS = [32]
BASE_CHS = [32]
LRS = [3e-4, 1e-4]
BATCH_SIZES = [64]
SPEC_TS = [176]
VAL_RATIOS = [0.1]

# Data feature hyperparams
N_MELS_VALUES = [128]
N_FFT_VALUES = [2048]
HOP_LENGTH_VALUES = [512]
FMIN = 0.0
FMAX = None

# Training/eval control
EPOCHS = 100
PATIENCE = 12
NUM_WORKERS = 2
SEED = 42
NOISE_STD = 0.5
GRIFFIN_ITERS = 60
MAX_RUNS = 6  # None for full grid
RUN_PREFIX = 'cae_nb'

PREPARE_AUDIO = False
MOVE_AUDIO_FILES = False
PREPARE_SPECS = False
FORCE_RECOMPUTE_SPECS = False
SKIP_EVAL = False

RUN_EXPERIMENTS = True  # switch to True to start training

In [7]:
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def to_jsonable(obj: Any) -> Any:
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, dict):
        return {k: to_jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_jsonable(v) for v in obj]
    if isinstance(obj, (np.integer, np.floating)):
        return obj.item()
    return obj


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(to_jsonable(payload), indent=2, ensure_ascii=False))


def save_history(path: Path, train_losses: list[float], val_losses: list[float]) -> None:
    rows = []
    for i, (tr, va) in enumerate(zip(train_losses, val_losses), start=1):
        rows.append({'epoch': i, 'train_l1': tr, 'val_l1': va})
    pd.DataFrame(rows).to_csv(path, index=False)


def make_run_name(run_idx: int, hp: dict[str, Any]) -> str:
    stamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    return (
        f"{RUN_PREFIX}_{run_idx:03d}_{stamp}"
        f"_lat{hp['latent_dim']}_lr{hp['lr']}_bs{hp['batch_size']}"
        f"_st{hp['spec_t']}_nm{hp['n_mels']}_fft{hp['n_fft']}_hop{hp['hop_length']}"
    )

In [5]:
grid = list(product(
    LATENT_DIMS, EMBED_DIMS, BASE_CHS, LRS, BATCH_SIZES, SPEC_TS, VAL_RATIOS,
    N_MELS_VALUES, N_FFT_VALUES, HOP_LENGTH_VALUES,
))
if MAX_RUNS is not None:
    grid = grid[:MAX_RUNS]

print('Planned runs:', len(grid))
for i, row in enumerate(grid[:10], start=1):
    print(i, row)
if len(grid) > 10:
    print('...')

if not RUN_EXPERIMENTS:
    print('RUN_EXPERIMENTS=False, this is a dry preview.')

Planned runs: 6
1 (64, 32, 32, 0.0003, 64, 176, 0.1, 128, 2048, 512)
2 (64, 32, 32, 0.0001, 64, 176, 0.1, 128, 2048, 512)
3 (128, 32, 32, 0.0003, 64, 176, 0.1, 128, 2048, 512)
4 (128, 32, 32, 0.0001, 64, 176, 0.1, 128, 2048, 512)
5 (256, 32, 32, 0.0003, 64, 176, 0.1, 128, 2048, 512)
6 (256, 32, 32, 0.0001, 64, 176, 0.1, 128, 2048, 512)

In [12]:
run_summaries: list[dict[str, Any]] = []

if RUN_EXPERIMENTS:
    if PREPARE_AUDIO:
        unpack_audio(AUDIO_DIR, AUDIO_UNPACKED_DIR, move_files=MOVE_AUDIO_FILES)

    prepared_specs: set[tuple[int, int, int]] = set()
    multiple_feature_variants = (len(N_MELS_VALUES) * len(N_FFT_VALUES) * len(HOP_LENGTH_VALUES)) > 1

    for run_idx, values in enumerate(grid, start=1):
        (latent_dim, embed_dim, base_ch, lr, batch_size, spec_t, val_ratio, n_mels, n_fft, hop_length) = values

        hp = {
            'latent_dim': latent_dim,
            'embed_dim': embed_dim,
            'base_ch': base_ch,
            'lr': lr,
            'batch_size': batch_size,
            'spec_t': spec_t,
            'val_ratio': val_ratio,
            'n_mels': n_mels,
            'n_fft': n_fft,
            'hop_length': hop_length,
        }

        run_name = make_run_name(run_idx, hp)
        run_dir = EXPERIMENTS_DIR / run_name
        tb_dir = run_dir / 'tb'
        ckpt_path = run_dir / 'checkpoints' / 'cae_best.pt'
        run_dir.mkdir(parents=True, exist_ok=True)

        spec_subdir = SPEC_ROOT / f"nm{n_mels}_fft{n_fft}_hop{hop_length}"
        if multiple_feature_variants or PREPARE_SPECS:
            spec_dir = spec_subdir
        else:
            has_flat_specs = SPEC_ROOT.exists() and any(SPEC_ROOT.glob('*.npy'))
            spec_dir = SPEC_ROOT if has_flat_specs else spec_subdir

        spec_key = (n_mels, n_fft, hop_length)
        if PREPARE_SPECS:
            needs_build = FORCE_RECOMPUTE_SPECS or (spec_key not in prepared_specs) or (not spec_dir.exists())
            if needs_build:
                print(f"[{run_idx}/{len(grid)}] Building spectrograms -> {spec_dir}")
                save_log_mel_spectrogram(
                    metadata=metadata,
                    audio_dir=AUDIO_UNPACKED_DIR,
                    output_dir=spec_dir,
                    n_mels=n_mels,
                    n_fft=n_fft,
                    hop_length=hop_length,
                    fmin=FMIN,
                    fmax=FMAX,
                )
                prepared_specs.add(spec_key)

        print(f"[{run_idx}/{len(grid)}] Run: {run_name}")
        set_seed(SEED + run_idx)

        train_cfg = TrainConfig(
            epochs=EPOCHS,
            lr=lr,
            batch_size=batch_size,
            num_workers=NUM_WORKERS,
            patience=PATIENCE,
            val_ratio=val_ratio,
            seed=SEED + run_idx,
            pin_memory=device.type == 'cuda',
            ckpt_path=ckpt_path,
            log_dir=tb_dir,
        )
        model_cfg = ModelConfig(
            n_classes=int(metadata['classID'].nunique()),
            embed_dim=embed_dim,
            latent_dim=latent_dim,
            base_ch=base_ch,
            spec_h=n_mels,
            spec_t=spec_t,
        )

        run_config = {
            'run_name': run_name,
            'run_dir': run_dir,
            'device': str(device),
            'data_dir': DATA_DIR,
            'audio_unpacked_dir': AUDIO_UNPACKED_DIR,
            'spec_dir': spec_dir,
            'train': asdict(train_cfg),
            'model': asdict(model_cfg),
            'eval': asdict(EvalConfig(batch_size=batch_size, noise_std=NOISE_STD, griffin_lim_iters=GRIFFIN_ITERS)),
        }
        write_json(run_dir / 'config.json', run_config)

        _, train_loader, val_loader = build_dataloaders(
            metadata=metadata,
            spec_dir=spec_dir,
            config=train_cfg,
            spec_t=spec_t,
        )

        model = ConditionalAE(config=model_cfg).to(device)
        params_count = count_trainable_parameters(model)
        print(f"  params={params_count:,} train_batches={len(train_loader)} val_batches={len(val_loader)}")

        train_result = train_model(
            model=model,
            train_loader=train_loader,
            val_loader=val_loader,
            device=device,
            config=train_cfg,
        )

        eval_metrics: dict[str, float] = {}
        if not SKIP_EVAL:
            eval_cfg = EvalConfig(batch_size=batch_size, noise_std=NOISE_STD, griffin_lim_iters=GRIFFIN_ITERS)
            eval_metrics = evaluate_model(
                model=model,
                val_loader=val_loader,
                device=device,
                config=eval_cfg,
                checkpoint_path=train_result['ckpt_path'],
            )

        metrics_payload = {
            'params_count': params_count,
            'best_val': train_result['best_val'],
            'best_epoch': train_result['best_epoch'],
            'train_epochs_ran': len(train_result['train_losses']),
            'eval': eval_metrics,
        }
        write_json(run_dir / 'metrics.json', metrics_payload)
        save_history(run_dir / 'history.csv', train_result['train_losses'], train_result['val_losses'])

        tb_writer = SummaryWriter(log_dir=str(tb_dir))
        for key, value in eval_metrics.items():
            tb_writer.add_scalar(f"Eval/{key}", value, int(train_result['best_epoch']))
        hparam_metrics = {'hparam/best_val': float(train_result['best_val'])}
        for key, value in eval_metrics.items():
            hparam_metrics[f"hparam/{key}"] = float(value)
        tb_writer.add_hparams(hp, hparam_metrics)
        tb_writer.close()

        row = {
            'run_name': run_name,
            'run_dir': str(run_dir),
            'spec_dir': str(spec_dir),
            'checkpoint': str(ckpt_path),
            'tb_dir': str(tb_dir),
            'params_count': params_count,
            'best_val': train_result['best_val'],
            'best_epoch': train_result['best_epoch'],
            **hp,
        }
        row.update(eval_metrics)
        run_summaries.append(row)

        print(f"  best_val={train_result['best_val']:.4f}")
        if eval_metrics:
            print(
                f"  eval logmel_l1={eval_metrics['logmel_l1']:.4f} "
                f"mr_stft={eval_metrics['mr_stft']:.4f} "
                f"si_sdr={eval_metrics['si_sdr']:.2f} fad={eval_metrics['fad']:.4f}"
            )
        print(f"  artifacts -> {run_dir}")

    summary_df = pd.DataFrame(run_summaries)
    summary_csv = EXPERIMENTS_DIR / 'summary.csv'
    summary_json = EXPERIMENTS_DIR / 'summary.json'
    summary_df.to_csv(summary_csv, index=False)
    write_json(summary_json, {'runs': run_summaries})

    print('Completed runs:', len(run_summaries))
    print('Summary CSV:', summary_csv)
    print('Summary JSON:', summary_json)
else:
    print('RUN_EXPERIMENTS=False, skipping training loop.')

[1/6] Run: cae_nb_001_20260228_190948_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512
Dataset: 8732 samples from /Users/kate/untitled folder 10/UrbanSound8K/spectrograms
  params=5,516,033 train_batches=123 val_batches=14

Training:  50%|█████     | 1/2 [06:59<06:59, 419.12s/it]

Epoch   1/2 train L1=0.1879 val L1=0.1231 lr=1.50e-04 es=0/12

Training: 100%|██████████| 2/2 [13:25<00:00, 402.75s/it]

Best val L1: 0.1158 (epoch=2, ckpt=/Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_001_20260228_190948_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt)
Loaded checkpoint: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_001_20260228_190948_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt

Collecting reconstructions: 100%|██████████| 14/14 [00:28<00:00,  2.07s/it]
Griffin-Lim: 100%|██████████| 873/873 [09:07<00:00,  1.59it/s]

  best_val=0.1158
  eval logmel_l1=0.1158 mr_stft=2.1177 si_sdr=-45.69 fad=18077.4295
  artifacts -> /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_001_20260228_190948_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512
[2/6] Run: cae_nb_002_20260228_193331_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512
Dataset: 8732 samples from /Users/kate/untitled folder 10/UrbanSound8K/spectrograms
  params=5,516,033 train_batches=123 val_batches=14

Training:  50%|█████     | 1/2 [06:00<06:00, 360.95s/it]

Epoch   1/2 train L1=0.2432 val L1=0.1537 lr=5.05e-05 es=0/12

Training: 100%|██████████| 2/2 [11:55<00:00, 357.82s/it]

Best val L1: 0.1296 (epoch=2, ckpt=/Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_002_20260228_193331_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt)
Loaded checkpoint: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_002_20260228_193331_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt

Collecting reconstructions: 100%|██████████| 14/14 [00:27<00:00,  1.99s/it]
Griffin-Lim: 100%|██████████| 873/873 [09:08<00:00,  1.59it/s]

  best_val=0.1296
  eval logmel_l1=0.1296 mr_stft=2.5739 si_sdr=-48.50 fad=6119.3491
  artifacts -> /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_002_20260228_193331_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512
[3/6] Run: cae_nb_003_20260228_195542_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512
Dataset: 8732 samples from /Users/kate/untitled folder 10/UrbanSound8K/spectrograms
  params=8,416,065 train_batches=123 val_batches=14

Training:  50%|█████     | 1/2 [06:11<06:11, 371.03s/it]

Epoch   1/2 train L1=0.1846 val L1=0.1307 lr=1.50e-04 es=0/12

Training: 100%|██████████| 2/2 [12:12<00:00, 366.49s/it]

Best val L1: 0.1099 (epoch=2, ckpt=/Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_003_20260228_195542_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt)
Loaded checkpoint: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_003_20260228_195542_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt

Collecting reconstructions: 100%|██████████| 14/14 [00:28<00:00,  2.01s/it]
Griffin-Lim: 100%|██████████| 873/873 [08:57<00:00,  1.62it/s]

  best_val=0.1099
  eval logmel_l1=0.1099 mr_stft=2.1025 si_sdr=-46.79 fad=31312.6553
  artifacts -> /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_003_20260228_195542_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512
[4/6] Run: cae_nb_004_20260228_201757_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512
Dataset: 8732 samples from /Users/kate/untitled folder 10/UrbanSound8K/spectrograms
  params=8,416,065 train_batches=123 val_batches=14

Training:  50%|█████     | 1/2 [06:13<06:13, 373.59s/it]

Epoch   1/2 train L1=0.2151 val L1=0.1410 lr=5.05e-05 es=0/12

Training: 100%|██████████| 2/2 [12:18<00:00, 369.00s/it]

Best val L1: 0.1190 (epoch=2, ckpt=/Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_004_20260228_201757_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt)
Loaded checkpoint: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_004_20260228_201757_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt

Collecting reconstructions: 100%|██████████| 14/14 [00:28<00:00,  2.04s/it]
Griffin-Lim: 100%|██████████| 873/873 [08:52<00:00,  1.64it/s]

  best_val=0.1190
  eval logmel_l1=0.1190 mr_stft=2.3779 si_sdr=-55.26 fad=9289.3735
  artifacts -> /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_004_20260228_201757_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512
[5/6] Run: cae_nb_005_20260228_204016_lat256_lr0.0003_bs64_st176_nm128_fft2048_hop512
Dataset: 8732 samples from /Users/kate/untitled folder 10/UrbanSound8K/spectrograms
  params=14,216,129 train_batches=123 val_batches=14

Training:  50%|█████     | 1/2 [06:10<06:10, 370.02s/it]

Epoch   1/2 train L1=0.1778 val L1=0.1237 lr=1.50e-04 es=0/12

Training: 100%|██████████| 2/2 [12:09<00:00, 364.58s/it]

Best val L1: 0.1081 (epoch=2, ckpt=/Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_005_20260228_204016_lat256_lr0.0003_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt)
Loaded checkpoint: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_005_20260228_204016_lat256_lr0.0003_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt

Collecting reconstructions: 100%|██████████| 14/14 [00:27<00:00,  2.00s/it]
Griffin-Lim: 100%|██████████| 873/873 [08:54<00:00,  1.63it/s]

  best_val=0.1081
  eval logmel_l1=0.1081 mr_stft=2.0958 si_sdr=-44.04 fad=41224.8465
  artifacts -> /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_005_20260228_204016_lat256_lr0.0003_bs64_st176_nm128_fft2048_hop512
[6/6] Run: cae_nb_006_20260228_210226_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512
Dataset: 8732 samples from /Users/kate/untitled folder 10/UrbanSound8K/spectrograms
  params=14,216,129 train_batches=123 val_batches=14

Training:  50%|█████     | 1/2 [06:09<06:09, 369.90s/it]

Epoch   1/2 train L1=0.1958 val L1=0.1216 lr=5.05e-05 es=0/12

Training: 100%|██████████| 2/2 [12:11<00:00, 365.71s/it]

Best val L1: 0.1094 (epoch=2, ckpt=/Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_006_20260228_210226_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt)
Loaded checkpoint: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_006_20260228_210226_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512/checkpoints/cae_best.pt

Collecting reconstructions: 100%|██████████| 14/14 [00:28<00:00,  2.01s/it]
Griffin-Lim: 100%|██████████| 873/873 [08:54<00:00,  1.63it/s]

  best_val=0.1094
  eval logmel_l1=0.1094 mr_stft=2.1259 si_sdr=-45.35 fad=14051.1832
  artifacts -> /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/cae_nb_006_20260228_210226_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512
Completed runs: 6
Summary CSV: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/summary.csv
Summary JSON: /Users/kate/untitled folder 10/s26_genai_project/experiments/cae/summary.json

In [13]:
summary_csv = EXPERIMENTS_DIR / 'summary.csv'
if summary_csv.exists():
    summary_df = pd.read_csv(summary_csv)
    cols = [
        c
        for c in [
            'run_name', 'latent_dim', 'embed_dim', 'base_ch', 'lr', 'batch_size',
            'spec_t', 'n_mels', 'n_fft', 'hop_length',
            'best_val', 'logmel_l1', 'mr_stft', 'si_sdr', 'fad',
        ]
        if c in summary_df.columns
    ]
    display(summary_df[cols].sort_values('best_val').reset_index(drop=True))
else:
    print('No summary.csv yet. Run experiments first.')

,run_name,latent_dim,embed_dim,base_ch,lr,batch_size,spec_t,n_mels,n_fft,hop_length,best_val,logmel_l1,mr_stft,si_sdr,fad
0,cae_nb_005_20260228_204016_lat256_lr0.0003_bs6...,256,32,32,0.0003,64,176,128,2048,512,0.108130,0.108130,2.095836,-44.041294,41224.846467
1,cae_nb_006_20260228_210226_lat256_lr0.0001_bs6...,256,32,32,0.0001,64,176,128,2048,512,0.109409,0.109409,2.125901,-45.352165,14051.183184
2,cae_nb_003_20260228_195542_lat128_lr0.0003_bs6...,128,32,32,0.0003,64,176,128,2048,512,0.109917,0.109917,2.102456,-46.794003,31312.655316
3,cae_nb_001_20260228_190948_lat64_lr0.0003_bs64...,64,32,32,0.0003,64,176,128,2048,512,0.115757,0.115757,2.117707,-45.687321,18077.429474
4,cae_nb_004_20260228_201757_lat128_lr0.0001_bs6...,128,32,32,0.0001,64,176,128,2048,512,0.118986,0.118986,2.377906,-55.257423,9289.373468
5,cae_nb_002_20260228_193331_lat64_lr0.0001_bs64...,64,32,32,0.0001,64,176,128,2048,512,0.129582,0.129582,2.573899,-48.503105,6119.349129

In [1]:
%load_ext tensorboard
%tensorboard --logdir experiments/cae

Launching TensorBoard...

## c-VAE experiments

In [4]:
from src.model import build_model

# VAE sweep config (same style as AE section)
VAE_LATENT_DIMS = LATENT_DIMS
VAE_EMBED_DIMS = EMBED_DIMS
VAE_BASE_CHS = BASE_CHS
VAE_LRS = LRS
VAE_BATCH_SIZES = BATCH_SIZES
VAE_SPEC_TS = SPEC_TS
VAE_VAL_RATIOS = VAL_RATIOS
VAE_N_MELS_VALUES = N_MELS_VALUES
VAE_N_FFT_VALUES = N_FFT_VALUES
VAE_HOP_LENGTH_VALUES = HOP_LENGTH_VALUES

# VAE-specific
VAE_BETA_KLS = [1e-3, 5e-3]
VAE_RUN_PREFIX = 'cvae_nb'
VAE_SKIP_EVAL = SKIP_EVAL
VAE_MAX_RUNS = MAX_RUNS

VAE_EXPERIMENTS_DIR = PROJECT_ROOT / 'experiments' / 'cvae'
VAE_EXPERIMENTS_DIR.mkdir(parents=True, exist_ok=True)

vae_grid = list(product(
    VAE_LATENT_DIMS, VAE_EMBED_DIMS, VAE_BASE_CHS, VAE_LRS, VAE_BATCH_SIZES, VAE_SPEC_TS, VAE_VAL_RATIOS,
    VAE_N_MELS_VALUES, VAE_N_FFT_VALUES, VAE_HOP_LENGTH_VALUES, VAE_BETA_KLS,
))
if VAE_MAX_RUNS is not None:
    vae_grid = random.choices(vae_grid, k=VAE_MAX_RUNS)

print('Planned VAE runs:', len(vae_grid))
for i, row in enumerate(vae_grid[:10], start=1):
    print(i, row)
if len(vae_grid) > 10:
    print('...')

Planned VAE runs: 6
1 (64, 32, 32, 0.0003, 64, 176, 0.1, 128, 2048, 512, 0.001)
2 (128, 32, 32, 0.0003, 64, 176, 0.1, 128, 2048, 512, 0.001)
3 (64, 32, 32, 0.0001, 64, 176, 0.1, 128, 2048, 512, 0.001)
4 (128, 32, 32, 0.0001, 64, 176, 0.1, 128, 2048, 512, 0.001)
5 (64, 32, 32, 0.0003, 64, 176, 0.1, 128, 2048, 512, 0.001)
6 (256, 32, 32, 0.0001, 64, 176, 0.1, 128, 2048, 512, 0.005)

In [ ]:
vae_run_summaries: list[dict[str, Any]] = []


if PREPARE_AUDIO:
    unpack_audio(AUDIO_DIR, AUDIO_UNPACKED_DIR, move_files=MOVE_AUDIO_FILES)

prepared_specs: set[tuple[int, int, int]] = set()
multiple_feature_variants = (
    len(VAE_N_MELS_VALUES) * len(VAE_N_FFT_VALUES) * len(VAE_HOP_LENGTH_VALUES)
) > 1

for run_idx, values in enumerate(vae_grid, start=1):
    if run_idx == 1:
        continue

    (
        latent_dim,
        embed_dim,
        base_ch,
        lr,
        batch_size,
        spec_t,
        val_ratio,
        n_mels,
        n_fft,
        hop_length,
        beta_kl,
    ) = values

    hp = {
        'latent_dim': latent_dim,
        'embed_dim': embed_dim,
        'base_ch': base_ch,
        'lr': lr,
        'batch_size': batch_size,
        'spec_t': spec_t,
        'val_ratio': val_ratio,
        'n_mels': n_mels,
        'n_fft': n_fft,
        'hop_length': hop_length,
        'beta_kl': beta_kl,
    }

    stamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    run_name = (
        f"{VAE_RUN_PREFIX}_{run_idx:03d}_{stamp}"
        f"_lat{latent_dim}_lr{lr}_bs{batch_size}"
        f"_st{spec_t}_nm{n_mels}_fft{n_fft}_hop{hop_length}_bkl{beta_kl}"
    )

    run_dir = VAE_EXPERIMENTS_DIR / run_name
    tb_dir = run_dir / 'tb'
    ckpt_path = run_dir / 'checkpoints' / 'cvae_best.pt'
    run_dir.mkdir(parents=True, exist_ok=True)

    spec_subdir = SPEC_ROOT / f"nm{n_mels}_fft{n_fft}_hop{hop_length}"
    if multiple_feature_variants or PREPARE_SPECS:
        spec_dir = spec_subdir
    else:
        has_flat_specs = SPEC_ROOT.exists() and any(SPEC_ROOT.glob('*.npy'))
        spec_dir = SPEC_ROOT if has_flat_specs else spec_subdir

    spec_key = (n_mels, n_fft, hop_length)
    if PREPARE_SPECS:
        needs_build = FORCE_RECOMPUTE_SPECS or (spec_key not in prepared_specs) or (not spec_dir.exists())
        if needs_build:
            print(f"[{run_idx}/{len(vae_grid)}] Building spectrograms -> {spec_dir}")
            save_log_mel_spectrogram(
                metadata=metadata,
                audio_dir=AUDIO_UNPACKED_DIR,
                output_dir=spec_dir,
                n_mels=n_mels,
                n_fft=n_fft,
                hop_length=hop_length,
                fmin=FMIN,
                fmax=FMAX,
            )
            prepared_specs.add(spec_key)

    print(f"[{run_idx}/{len(vae_grid)}] VAE Run: {run_name}")
    set_seed(SEED + run_idx)

    train_cfg = TrainConfig(
        model_type='vae',
        epochs=EPOCHS,
        lr=lr,
        beta_kl=beta_kl,
        batch_size=batch_size,
        num_workers=NUM_WORKERS,
        patience=PATIENCE,
        val_ratio=val_ratio,
        seed=SEED + run_idx,
        pin_memory=device.type == 'cuda',
        ckpt_path=ckpt_path,
        log_dir=tb_dir,
    )
    model_cfg = ModelConfig(
        n_classes=int(metadata['classID'].nunique()),
        embed_dim=embed_dim,
        latent_dim=latent_dim,
        base_ch=base_ch,
        spec_h=n_mels,
        spec_t=spec_t,
    )

    run_config = {
        'run_name': run_name,
        'run_dir': run_dir,
        'device': str(device),
        'data_dir': DATA_DIR,
        'audio_unpacked_dir': AUDIO_UNPACKED_DIR,
        'spec_dir': spec_dir,
        'train': asdict(train_cfg),
        'model': asdict(model_cfg),
        'eval': asdict(EvalConfig(batch_size=batch_size, noise_std=NOISE_STD, griffin_lim_iters=GRIFFIN_ITERS)),
    }
    write_json(run_dir / 'config.json', run_config)

    _, train_loader, val_loader = build_dataloaders(
        metadata=metadata,
        spec_dir=spec_dir,
        config=train_cfg,
        spec_t=spec_t,
    )

    model = build_model(model_type='vae', config=model_cfg).to(device)
    params_count = count_trainable_parameters(model)
    print(f"  params={params_count:,} train_batches={len(train_loader)} val_batches={len(val_loader)}")

    train_result = train_model(
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        device=device,
        config=train_cfg,
    )

    eval_metrics: dict[str, float] = {}
    if not VAE_SKIP_EVAL:
        eval_cfg = EvalConfig(batch_size=batch_size, noise_std=NOISE_STD, griffin_lim_iters=GRIFFIN_ITERS)
        eval_metrics = evaluate_model(
            model=model,
            val_loader=val_loader,
            device=device,
            config=eval_cfg,
            checkpoint_path=train_result['ckpt_path'],
        )

    metrics_payload = {
        'params_count': params_count,
        'best_val': train_result['best_val'],
        'best_epoch': train_result['best_epoch'],
        'train_epochs_ran': len(train_result['train_losses']),
        'eval': eval_metrics,
    }
    write_json(run_dir / 'metrics.json', metrics_payload)
    save_history(run_dir / 'history.csv', train_result['train_losses'], train_result['val_losses'])

    tb_writer = SummaryWriter(log_dir=str(tb_dir))
    for key, value in eval_metrics.items():
        tb_writer.add_scalar(f"Eval/{key}", value, int(train_result['best_epoch']))
    hparam_metrics = {'hparam/best_val': float(train_result['best_val'])}
    for key, value in eval_metrics.items():
        hparam_metrics[f"hparam/{key}"] = float(value)
    tb_writer.add_hparams(hp, hparam_metrics)
    tb_writer.close()

    row = {
        'run_name': run_name,
        'run_dir': str(run_dir),
        'spec_dir': str(spec_dir),
        'checkpoint': str(ckpt_path),
        'tb_dir': str(tb_dir),
        'params_count': params_count,
        'best_val': train_result['best_val'],
        'best_epoch': train_result['best_epoch'],
        **hp,
    }
    row.update(eval_metrics)
    vae_run_summaries.append(row)

    print(f"  best_val={train_result['best_val']:.4f}")
    if eval_metrics:
        print(
            f"  eval logmel_l1={eval_metrics['logmel_l1']:.4f} "
            f"mr_stft={eval_metrics['mr_stft']:.4f} "
            f"si_sdr={eval_metrics['si_sdr']:.2f} fad={eval_metrics['fad']:.4f}"
        )
    print(f"  artifacts -> {run_dir}")

vae_summary_df = pd.DataFrame(vae_run_summaries)
vae_summary_csv = VAE_EXPERIMENTS_DIR / 'summary.csv'
vae_summary_json = VAE_EXPERIMENTS_DIR / 'summary.json'
vae_summary_df.to_csv(vae_summary_csv, index=False)
write_json(vae_summary_json, {'runs': vae_run_summaries})

print('Completed VAE runs:', len(vae_run_summaries))
print('VAE Summary CSV:', vae_summary_csv)
print('VAE Summary JSON:', vae_summary_json)

[2/6] VAE Run: cvae_nb_002_20260319_003524_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=11,332,545 train_batches=123 val_batches=14
  params=11,332,545 train_batches=123 val_batches=14
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved

Training:   1%|▌                                                       | 1/100 [00:18<31:03, 18.83s/it]

Epoch   1/100 train total=0.2640 recon=0.2156 kl=48.3546 val total=0.1630 recon=0.1427 kl=20.3439 lr=3.00e-04 es=0/12

Training:   5%|██▊                                                     | 5/100 [01:31<28:43, 18.14s/it]

Epoch   5/100 train total=0.1365 recon=0.1216 kl=14.9247 val total=0.1314 recon=0.1176 kl=13.8116 lr=2.98e-04 es=0/12

Training:  10%|█████▌                                                 | 10/100 [03:01<27:21, 18.24s/it]

Epoch  10/100 train total=0.1266 recon=0.1126 kl=14.0335 val total=0.1233 recon=0.1091 kl=14.1687 lr=2.93e-04 es=0/12

Training:  15%|████████▎                                              | 15/100 [04:32<25:37, 18.09s/it]

Epoch  15/100 train total=0.1210 recon=0.1073 kl=13.6562 val total=0.1189 recon=0.1052 kl=13.7306 lr=2.84e-04 es=1/12

Training:  20%|███████████                                            | 20/100 [06:03<24:21, 18.27s/it]

Epoch  20/100 train total=0.1175 recon=0.1038 kl=13.6953 val total=0.1151 recon=0.1016 kl=13.5029 lr=2.71e-04 es=0/12

Training:  25%|█████████████▊                                         | 25/100 [07:34<22:46, 18.22s/it]

Epoch  25/100 train total=0.1147 recon=0.1009 kl=13.8049 val total=0.1135 recon=0.1001 kl=13.4123 lr=2.56e-04 es=0/12

Training:  30%|████████████████▌                                      | 30/100 [09:05<21:25, 18.36s/it]

Epoch  30/100 train total=0.1134 recon=0.0995 kl=13.8857 val total=0.1126 recon=0.0988 kl=13.7276 lr=2.38e-04 es=2/12

Training:  35%|███████████████████▎                                   | 35/100 [10:37<19:50, 18.31s/it]

Epoch  35/100 train total=0.1119 recon=0.0980 kl=13.8559 val total=0.1111 recon=0.0970 kl=14.0927 lr=2.18e-04 es=1/12

Training:  40%|██████████████████████                                 | 40/100 [12:09<18:22, 18.38s/it]

Epoch  40/100 train total=0.1108 recon=0.0969 kl=13.8213 val total=0.1112 recon=0.0973 kl=13.8445 lr=1.97e-04 es=4/12

Training:  45%|████████████████████████▊                              | 45/100 [13:40<16:46, 18.30s/it]

Epoch  45/100 train total=0.1094 recon=0.0954 kl=13.9599 val total=0.1096 recon=0.0957 kl=13.8703 lr=1.74e-04 es=1/12

Training:  50%|███████████████████████████▌                           | 50/100 [15:11<15:18, 18.37s/it]

Epoch  50/100 train total=0.1091 recon=0.0951 kl=13.9727 val total=0.1091 recon=0.0952 kl=13.8842 lr=1.50e-04 es=3/12

Training:  55%|██████████████████████████████▎                        | 55/100 [16:42<13:34, 18.10s/it]

Epoch  55/100 train total=0.1080 recon=0.0940 kl=13.9903 val total=0.1085 recon=0.0948 kl=13.7494 lr=1.27e-04 es=2/12

Training:  60%|█████████████████████████████████                      | 60/100 [18:12<12:05, 18.13s/it]

Epoch  60/100 train total=0.1072 recon=0.0932 kl=13.9835 val total=0.1077 recon=0.0940 kl=13.7584 lr=1.04e-04 es=3/12

Training:  65%|███████████████████████████████████▊                   | 65/100 [19:43<10:35, 18.17s/it]

Epoch  65/100 train total=0.1066 recon=0.0927 kl=13.9040 val total=0.1073 recon=0.0936 kl=13.7667 lr=8.26e-05 es=4/12

Training:  70%|██████████████████████████████████████▌                | 70/100 [21:15<09:11, 18.39s/it]

Epoch  70/100 train total=0.1062 recon=0.0922 kl=13.9860 val total=0.1070 recon=0.0932 kl=13.8049 lr=6.26e-05 es=2/12

Training:  75%|█████████████████████████████████████████▎             | 75/100 [22:46<07:37, 18.30s/it]

Epoch  75/100 train total=0.1058 recon=0.0918 kl=13.9674 val total=0.1067 recon=0.0927 kl=14.0139 lr=4.48e-05 es=3/12

Training:  80%|████████████████████████████████████████████           | 80/100 [24:19<06:09, 18.47s/it]

Epoch  80/100 train total=0.1053 recon=0.0914 kl=13.9318 val total=0.1060 recon=0.0921 kl=13.8563 lr=2.96e-05 es=0/12

Training:  85%|██████████████████████████████████████████████▊        | 85/100 [25:50<04:35, 18.34s/it]

Epoch  85/100 train total=0.1052 recon=0.0912 kl=13.9458 val total=0.1062 recon=0.0923 kl=13.8362 lr=1.73e-05 es=5/12

Training:  90%|█████████████████████████████████████████████████▌     | 90/100 [27:22<03:04, 18.46s/it]

Epoch  90/100 train total=0.1048 recon=0.0909 kl=13.8789 val total=0.1062 recon=0.0924 kl=13.8336 lr=8.32e-06 es=10/12

Training:  91%|██████████████████████████████████████████████████     | 91/100 [27:59<02:46, 18.45s/it]

Early stopping at epoch 92 (patience=12).
Best val L1: 0.1060 (epoch=80, ckpt=/home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_002_20260319_003524_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt)
Loaded checkpoint: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_002_20260319_003524_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt

Collecting reconstructions:   0%|          | 0/14 [00:00<?, ?it/s]

Griffin-Lim:   0%|          | 0/873 [00:00<?, ?it/s]

  best_val=0.1060
  eval logmel_l1=0.0925 mr_stft=1.9072 si_sdr=-42.79 fad=3.3379
  artifacts -> /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_002_20260319_003524_lat128_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001
[3/6] VAE Run: cvae_nb_003_20260319_011350_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=6,974,273 train_batches=123 val_batches=14
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=6,974,273 train_batches=123 val_batches=14
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved

Training:   1%|▌                                                       | 1/100 [00:18<30:36, 18.55s/it]

Epoch   1/100 train total=0.2774 recon=0.2537 kl=23.6595 val total=0.1879 recon=0.1649 kl=23.0586 lr=1.00e-04 es=0/12

Training:   5%|██▊                                                     | 5/100 [01:30<28:25, 17.96s/it]

Epoch   5/100 train total=0.1391 recon=0.1228 kl=16.2684 val total=0.1327 recon=0.1179 kl=14.7885 lr=9.94e-05 es=0/12

Training:  10%|█████▌                                                 | 10/100 [03:01<27:40, 18.45s/it]

Epoch  10/100 train total=0.1266 recon=0.1120 kl=14.5954 val total=0.1244 recon=0.1099 kl=14.5063 lr=9.76e-05 es=0/12

Training:  15%|████████▎                                              | 15/100 [04:30<25:28, 17.98s/it]

Epoch  15/100 train total=0.1213 recon=0.1068 kl=14.5137 val total=0.1187 recon=0.1049 kl=13.7991 lr=9.46e-05 es=0/12

Training:  20%|███████████                                            | 20/100 [06:00<23:56, 17.96s/it]

Epoch  20/100 train total=0.1199 recon=0.1056 kl=14.3199 val total=0.1168 recon=0.1030 kl=13.8105 lr=9.05e-05 es=0/12

Training:  25%|█████████████▊                                         | 25/100 [07:30<22:32, 18.03s/it]

Epoch  25/100 train total=0.1169 recon=0.1025 kl=14.3327 val total=0.1157 recon=0.1014 kl=14.3008 lr=8.55e-05 es=1/12

Training:  30%|████████████████▌                                      | 30/100 [09:01<21:16, 18.24s/it]

Epoch  30/100 train total=0.1161 recon=0.1018 kl=14.2901 val total=0.1144 recon=0.1008 kl=13.6726 lr=7.96e-05 es=0/12

Training:  35%|███████████████████▎                                   | 35/100 [10:32<19:41, 18.17s/it]

Epoch  35/100 train total=0.1142 recon=0.0998 kl=14.4181 val total=0.1147 recon=0.1009 kl=13.7880 lr=7.30e-05 es=1/12

Training:  40%|██████████████████████                                 | 40/100 [12:03<18:17, 18.29s/it]

Epoch  40/100 train total=0.1129 recon=0.0986 kl=14.3423 val total=0.1145 recon=0.1004 kl=14.0352 lr=6.58e-05 es=2/12

Training:  45%|████████████████████████▊                              | 45/100 [13:33<16:34, 18.08s/it]

Epoch  45/100 train total=0.1122 recon=0.0978 kl=14.3687 val total=0.1122 recon=0.0980 kl=14.2400 lr=5.82e-05 es=0/12

Training:  50%|███████████████████████████▌                           | 50/100 [15:04<15:10, 18.21s/it]

Epoch  50/100 train total=0.1115 recon=0.0970 kl=14.4407 val total=0.1119 recon=0.0974 kl=14.5021 lr=5.05e-05 es=3/12

Training:  55%|██████████████████████████████▎                        | 55/100 [16:34<13:30, 18.01s/it]

Epoch  55/100 train total=0.1110 recon=0.0965 kl=14.4909 val total=0.1111 recon=0.0970 kl=14.0987 lr=4.28e-05 es=0/12

Training:  60%|█████████████████████████████████                      | 60/100 [18:04<12:05, 18.13s/it]

Epoch  60/100 train total=0.1104 recon=0.0960 kl=14.4720 val total=0.1108 recon=0.0962 kl=14.6395 lr=3.52e-05 es=0/12

Training:  65%|███████████████████████████████████▊                   | 65/100 [19:34<10:29, 17.99s/it]

Epoch  65/100 train total=0.1100 recon=0.0955 kl=14.4795 val total=0.1109 recon=0.0965 kl=14.3867 lr=2.80e-05 es=5/12

Training:  70%|██████████████████████████████████████▌                | 70/100 [21:04<09:02, 18.08s/it]

Epoch  70/100 train total=0.1096 recon=0.0951 kl=14.4638 val total=0.1105 recon=0.0962 kl=14.2731 lr=2.14e-05 es=4/12

Training:  75%|█████████████████████████████████████████▎             | 75/100 [22:34<07:28, 17.95s/it]

Epoch  75/100 train total=0.1094 recon=0.0949 kl=14.4955 val total=0.1104 recon=0.0963 kl=14.0421 lr=1.55e-05 es=9/12

Training:  80%|████████████████████████████████████████████           | 80/100 [24:04<05:59, 18.00s/it]

Epoch  80/100 train total=0.1089 recon=0.0943 kl=14.5280 val total=0.1098 recon=0.0955 kl=14.3008 lr=1.05e-05 es=0/12

Training:  85%|██████████████████████████████████████████████▊        | 85/100 [25:33<04:29, 17.94s/it]

Epoch  85/100 train total=0.1088 recon=0.0943 kl=14.5541 val total=0.1099 recon=0.0956 kl=14.3137 lr=6.40e-06 es=3/12

Training:  90%|█████████████████████████████████████████████████▌     | 90/100 [27:03<03:00, 18.04s/it]

Epoch  90/100 train total=0.1085 recon=0.0940 kl=14.5205 val total=0.1098 recon=0.0957 kl=14.1270 lr=3.42e-06 es=8/12

Training:  95%|████████████████████████████████████████████████████▎  | 95/100 [28:33<01:29, 17.96s/it]

Epoch  95/100 train total=0.1085 recon=0.0940 kl=14.5580 val total=0.1098 recon=0.0956 kl=14.2617 lr=1.61e-06 es=1/12

Training: 100%|██████████████████████████████████████████████████████| 100/100 [30:03<00:00, 18.04s/it]

Epoch 100/100 train total=0.1086 recon=0.0940 kl=14.5771 val total=0.1097 recon=0.0955 kl=14.2150 lr=1.00e-06 es=6/12
Best val L1: 0.1095 (epoch=94, ckpt=/home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_003_20260319_011350_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt)
Loaded checkpoint: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_003_20260319_011350_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt

Collecting reconstructions:   0%|          | 0/14 [00:00<?, ?it/s]

Griffin-Lim:   0%|          | 0/873 [00:00<?, ?it/s]

  best_val=0.1095
  eval logmel_l1=0.0957 mr_stft=1.9288 si_sdr=-43.42 fad=3.5746
  artifacts -> /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_003_20260319_011350_lat64_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001
[4/6] VAE Run: cvae_nb_004_20260319_015341_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=11,332,545 train_batches=123 val_batches=14
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=11,332,545 train_batches=123 val_batches=14
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved

Training:   1%|▌                                                       | 1/100 [00:18<30:50, 18.69s/it]

Epoch   1/100 train total=0.2865 recon=0.2601 kl=26.3955 val total=0.1879 recon=0.1661 kl=21.8069 lr=1.00e-04 es=0/12

Training:   5%|██▊                                                     | 5/100 [01:30<28:38, 18.09s/it]

Epoch   5/100 train total=0.1455 recon=0.1287 kl=16.7881 val total=0.1373 recon=0.1217 kl=15.5723 lr=9.94e-05 es=0/12

Training:  10%|█████▌                                                 | 10/100 [03:01<27:10, 18.11s/it]

Epoch  10/100 train total=0.1291 recon=0.1146 kl=14.5716 val total=0.1274 recon=0.1133 kl=14.0769 lr=9.76e-05 es=1/12

Training:  15%|████████▎                                              | 15/100 [04:31<25:34, 18.05s/it]

Epoch  15/100 train total=0.1236 recon=0.1092 kl=14.3618 val total=0.1214 recon=0.1068 kl=14.5521 lr=9.46e-05 es=1/12

Training:  20%|███████████                                            | 20/100 [06:02<24:19, 18.24s/it]

Epoch  20/100 train total=0.1212 recon=0.1070 kl=14.2061 val total=0.1191 recon=0.1049 kl=14.2682 lr=9.05e-05 es=0/12

Training:  25%|█████████████▊                                         | 25/100 [07:32<22:37, 18.11s/it]

Epoch  25/100 train total=0.1191 recon=0.1049 kl=14.2522 val total=0.1187 recon=0.1042 kl=14.5283 lr=8.55e-05 es=0/12

Training:  30%|████████████████▌                                      | 30/100 [09:03<21:12, 18.17s/it]

Epoch  30/100 train total=0.1180 recon=0.1037 kl=14.2572 val total=0.1182 recon=0.1040 kl=14.1524 lr=7.96e-05 es=1/12

Training:  35%|███████████████████▎                                   | 35/100 [10:33<19:34, 18.06s/it]

Epoch  35/100 train total=0.1165 recon=0.1023 kl=14.1560 val total=0.1162 recon=0.1019 kl=14.3271 lr=7.30e-05 es=0/12

Training:  40%|██████████████████████                                 | 40/100 [12:03<18:07, 18.13s/it]

Epoch  40/100 train total=0.1152 recon=0.1010 kl=14.2409 val total=0.1147 recon=0.1005 kl=14.1461 lr=6.58e-05 es=0/12

Training:  45%|████████████████████████▊                              | 45/100 [13:33<16:29, 17.98s/it]

Epoch  45/100 train total=0.1144 recon=0.1002 kl=14.2665 val total=0.1150 recon=0.1005 kl=14.4533 lr=5.82e-05 es=5/12

Training:  50%|███████████████████████████▌                           | 50/100 [15:03<15:03, 18.07s/it]

Epoch  50/100 train total=0.1138 recon=0.0995 kl=14.2565 val total=0.1138 recon=0.0998 kl=13.9972 lr=5.05e-05 es=1/12

Training:  55%|██████████████████████████████▎                        | 55/100 [16:33<13:31, 18.04s/it]

Epoch  55/100 train total=0.1131 recon=0.0987 kl=14.3429 val total=0.1132 recon=0.0989 kl=14.2906 lr=4.28e-05 es=0/12

Training:  60%|█████████████████████████████████                      | 60/100 [18:03<12:02, 18.05s/it]

Epoch  60/100 train total=0.1122 recon=0.0979 kl=14.2888 val total=0.1131 recon=0.0987 kl=14.4049 lr=3.52e-05 es=1/12

Training:  65%|███████████████████████████████████▊                   | 65/100 [19:33<10:30, 18.02s/it]

Epoch  65/100 train total=0.1119 recon=0.0976 kl=14.3398 val total=0.1126 recon=0.0983 kl=14.2370 lr=2.80e-05 es=0/12

Training:  70%|██████████████████████████████████████▌                | 70/100 [21:04<09:06, 18.22s/it]

Epoch  70/100 train total=0.1114 recon=0.0970 kl=14.3674 val total=0.1123 recon=0.0981 kl=14.2524 lr=2.14e-05 es=1/12

Training:  75%|█████████████████████████████████████████▎             | 75/100 [22:35<07:33, 18.12s/it]

Epoch  75/100 train total=0.1109 recon=0.0965 kl=14.3938 val total=0.1119 recon=0.0976 kl=14.3636 lr=1.55e-05 es=3/12

Training:  80%|████████████████████████████████████████████           | 80/100 [24:07<06:08, 18.43s/it]

Epoch  80/100 train total=0.1106 recon=0.0962 kl=14.3648 val total=0.1115 recon=0.0971 kl=14.3309 lr=1.05e-05 es=0/12

Training:  85%|██████████████████████████████████████████████▊        | 85/100 [25:38<04:34, 18.28s/it]

Epoch  85/100 train total=0.1107 recon=0.0963 kl=14.4072 val total=0.1112 recon=0.0969 kl=14.2863 lr=6.40e-06 es=0/12

Training:  90%|█████████████████████████████████████████████████▌     | 90/100 [27:09<03:03, 18.37s/it]

Epoch  90/100 train total=0.1102 recon=0.0958 kl=14.4235 val total=0.1118 recon=0.0974 kl=14.4342 lr=3.42e-06 es=5/12

Training:  95%|████████████████████████████████████████████████████▎  | 95/100 [28:40<01:31, 18.24s/it]

Epoch  95/100 train total=0.1101 recon=0.0957 kl=14.4035 val total=0.1115 recon=0.0971 kl=14.3538 lr=1.61e-06 es=10/12

Training:  96%|████████████████████████████████████████████████████▊  | 96/100 [29:17<01:13, 18.31s/it]

Early stopping at epoch 97 (patience=12).
Best val L1: 0.1112 (epoch=85, ckpt=/home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_004_20260319_015341_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt)
Loaded checkpoint: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_004_20260319_015341_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt

Collecting reconstructions:   0%|          | 0/14 [00:00<?, ?it/s]

Griffin-Lim:   0%|          | 0/873 [00:00<?, ?it/s]

  best_val=0.1112
  eval logmel_l1=0.0972 mr_stft=1.9461 si_sdr=-44.38 fad=3.8941
  artifacts -> /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_004_20260319_015341_lat128_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.001
[5/6] VAE Run: cvae_nb_005_20260319_023146_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=6,974,273 train_batches=123 val_batches=14
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=6,974,273 train_batches=123 val_batches=14
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved

Training:   1%|▌                                                       | 1/100 [00:18<29:47, 18.06s/it]

Epoch   1/100 train total=0.2560 recon=0.2171 kl=38.8849 val total=0.1616 recon=0.1426 kl=19.0556 lr=3.00e-04 es=0/12

Training:   5%|██▊                                                     | 5/100 [01:28<28:00, 17.68s/it]

Epoch   5/100 train total=0.1361 recon=0.1212 kl=14.9124 val total=0.1296 recon=0.1148 kl=14.8398 lr=2.98e-04 es=0/12

Training:  10%|█████▌                                                 | 10/100 [02:57<26:37, 17.75s/it]

Epoch  10/100 train total=0.1249 recon=0.1104 kl=14.4440 val total=0.1193 recon=0.1053 kl=13.9920 lr=2.93e-04 es=0/12

Training:  15%|████████▎                                              | 15/100 [04:25<24:59, 17.65s/it]

Epoch  15/100 train total=0.1204 recon=0.1061 kl=14.2797 val total=0.1168 recon=0.1038 kl=13.0331 lr=2.84e-04 es=0/12

Training:  20%|███████████                                            | 20/100 [05:53<23:38, 17.73s/it]

Epoch  20/100 train total=0.1178 recon=0.1036 kl=14.1882 val total=0.1139 recon=0.0999 kl=13.9309 lr=2.71e-04 es=0/12

Training:  25%|█████████████▊                                         | 25/100 [07:21<22:02, 17.64s/it]

Epoch  25/100 train total=0.1160 recon=0.1018 kl=14.1991 val total=0.1168 recon=0.1036 kl=13.1619 lr=2.56e-04 es=2/12

Training:  30%|████████████████▌                                      | 30/100 [08:50<20:46, 17.80s/it]

Epoch  30/100 train total=0.1130 recon=0.0988 kl=14.1933 val total=0.1115 recon=0.0976 kl=13.8858 lr=2.38e-04 es=1/12

Training:  35%|███████████████████▎                                   | 35/100 [10:19<19:14, 17.76s/it]

Epoch  35/100 train total=0.1132 recon=0.0990 kl=14.2007 val total=0.1131 recon=0.0995 kl=13.5436 lr=2.18e-04 es=2/12

Training:  40%|██████████████████████                                 | 40/100 [11:48<17:53, 17.90s/it]

Epoch  40/100 train total=0.1117 recon=0.0975 kl=14.1693 val total=0.1103 recon=0.0963 kl=14.0020 lr=1.97e-04 es=0/12

Training:  45%|████████████████████████▊                              | 45/100 [13:17<16:23, 17.88s/it]

Epoch  45/100 train total=0.1104 recon=0.0961 kl=14.2478 val total=0.1099 recon=0.0961 kl=13.7740 lr=1.74e-04 es=2/12

Training:  50%|███████████████████████████▌                           | 50/100 [14:47<14:57, 17.94s/it]

Epoch  50/100 train total=0.1095 recon=0.0953 kl=14.2117 val total=0.1093 recon=0.0955 kl=13.7744 lr=1.50e-04 es=4/12

Training:  55%|██████████████████████████████▎                        | 55/100 [16:16<13:25, 17.90s/it]

Epoch  55/100 train total=0.1088 recon=0.0946 kl=14.2349 val total=0.1082 recon=0.0946 kl=13.5851 lr=1.27e-04 es=0/12

Training:  60%|█████████████████████████████████                      | 60/100 [17:46<12:03, 18.10s/it]

Epoch  60/100 train total=0.1077 recon=0.0934 kl=14.3027 val total=0.1080 recon=0.0941 kl=13.8844 lr=1.04e-04 es=1/12

Training:  65%|███████████████████████████████████▊                   | 65/100 [19:16<10:28, 17.95s/it]

Epoch  65/100 train total=0.1071 recon=0.0928 kl=14.2893 val total=0.1070 recon=0.0931 kl=13.8998 lr=8.26e-05 es=0/12

Training:  70%|██████████████████████████████████████▌                | 70/100 [20:46<09:01, 18.06s/it]

Epoch  70/100 train total=0.1068 recon=0.0926 kl=14.2803 val total=0.1068 recon=0.0930 kl=13.7844 lr=6.26e-05 es=0/12

Training:  75%|█████████████████████████████████████████▎             | 75/100 [22:16<07:30, 18.04s/it]

Epoch  75/100 train total=0.1060 recon=0.0916 kl=14.3299 val total=0.1064 recon=0.0925 kl=13.9642 lr=4.48e-05 es=0/12

Training:  80%|████████████████████████████████████████████           | 80/100 [23:46<06:01, 18.10s/it]

Epoch  80/100 train total=0.1056 recon=0.0913 kl=14.3215 val total=0.1062 recon=0.0923 kl=13.9284 lr=2.96e-05 es=0/12

Training:  85%|██████████████████████████████████████████████▊        | 85/100 [25:16<04:29, 17.99s/it]

Epoch  85/100 train total=0.1054 recon=0.0910 kl=14.3805 val total=0.1064 recon=0.0925 kl=13.9533 lr=1.73e-05 es=5/12

Training:  90%|█████████████████████████████████████████████████▌     | 90/100 [26:46<03:00, 18.04s/it]

Epoch  90/100 train total=0.1053 recon=0.0909 kl=14.3932 val total=0.1061 recon=0.0921 kl=14.0620 lr=8.32e-06 es=4/12

Training:  95%|████████████████████████████████████████████████████▎  | 95/100 [28:16<01:29, 17.96s/it]

Epoch  95/100 train total=0.1051 recon=0.0907 kl=14.3835 val total=0.1061 recon=0.0920 kl=14.0558 lr=2.84e-06 es=1/12

Training: 100%|██████████████████████████████████████████████████████| 100/100 [29:46<00:00, 17.86s/it]

Epoch 100/100 train total=0.1049 recon=0.0906 kl=14.3866 val total=0.1059 recon=0.0918 kl=14.1027 lr=1.00e-06 es=6/12
Best val L1: 0.1058 (epoch=94, ckpt=/home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_005_20260319_023146_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt)
Loaded checkpoint: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_005_20260319_023146_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001/checkpoints/cvae_best.pt

Collecting reconstructions:   0%|          | 0/14 [00:00<?, ?it/s]

Griffin-Lim:   0%|          | 0/873 [00:00<?, ?it/s]

  best_val=0.1058
  eval logmel_l1=0.0918 mr_stft=1.8971 si_sdr=-42.20 fad=3.0198
  artifacts -> /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_005_20260319_023146_lat64_lr0.0003_bs64_st176_nm128_fft2048_hop512_bkl0.001
[6/6] VAE Run: cvae_nb_006_20260319_031056_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.005
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=20,049,089 train_batches=123 val_batches=14
Dataset: 8732 samples from /mnt/shared/gen_ai_proj_data/UrbanSound8K/spectrograms
  params=20,049,089 train_batches=123 val_batches=14
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved
Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
Error occurs, No graph saved

Training:   1%|▌                                                       | 1/100 [00:19<31:39, 19.19s/it]

Epoch   1/100 train total=0.3575 recon=0.2991 kl=11.6862 val total=0.2343 recon=0.2052 kl=5.8328 lr=1.00e-04 es=0/12

Training:   5%|██▊                                                     | 5/100 [01:33<29:23, 18.56s/it]

Epoch   5/100 train total=0.1922 recon=0.1663 kl=5.1688 val total=0.1861 recon=0.1577 kl=5.6797 lr=9.94e-05 es=0/12

Training:  10%|█████▌                                                 | 10/100 [03:06<28:05, 18.73s/it]

Epoch  10/100 train total=0.1690 recon=0.1469 kl=4.4138 val total=0.1661 recon=0.1435 kl=4.5178 lr=9.76e-05 es=0/12

Training:  15%|████████▎                                              | 15/100 [04:39<26:18, 18.57s/it]

Epoch  15/100 train total=0.1627 recon=0.1412 kl=4.3193 val total=0.1604 recon=0.1383 kl=4.4247 lr=9.46e-05 es=2/12

Training:  20%|███████████                                            | 20/100 [06:12<24:55, 18.70s/it]

Epoch  20/100 train total=0.1582 recon=0.1361 kl=4.4143 val total=0.1543 recon=0.1312 kl=4.6375 lr=9.05e-05 es=0/12

Training:  25%|█████████████▊                                         | 25/100 [07:45<23:14, 18.59s/it]

Epoch  25/100 train total=0.1543 recon=0.1319 kl=4.4764 val total=0.1518 recon=0.1295 kl=4.4635 lr=8.55e-05 es=2/12

Training:  30%|████████████████▌                                      | 30/100 [09:18<21:44, 18.64s/it]

Epoch  30/100 train total=0.1522 recon=0.1300 kl=4.4335 val total=0.1515 recon=0.1281 kl=4.6811 lr=7.96e-05 es=3/12

Training:  35%|███████████████████▎                                   | 35/100 [10:51<20:04, 18.52s/it]

Epoch  35/100 train total=0.1504 recon=0.1280 kl=4.4778 val total=0.1514 recon=0.1289 kl=4.5106 lr=7.30e-05 es=3/12

Training:  40%|██████████████████████                                 | 40/100 [12:24<18:39, 18.65s/it]

Epoch  40/100 train total=0.1500 recon=0.1277 kl=4.4690 val total=0.1473 recon=0.1251 kl=4.4356 lr=6.58e-05 es=0/12

Training:  45%|████████████████████████▊                              | 45/100 [13:56<16:54, 18.44s/it]

Epoch  45/100 train total=0.1480 recon=0.1257 kl=4.4544 val total=0.1484 recon=0.1264 kl=4.3979 lr=5.82e-05 es=2/12

Training:  50%|███████████████████████████▌                           | 50/100 [15:28<15:26, 18.54s/it]

Epoch  50/100 train total=0.1471 recon=0.1247 kl=4.4697 val total=0.1460 recon=0.1235 kl=4.4986 lr=5.05e-05 es=1/12

Training:  55%|██████████████████████████████▎                        | 55/100 [17:01<13:51, 18.48s/it]

Epoch  55/100 train total=0.1459 recon=0.1238 kl=4.4255 val total=0.1450 recon=0.1232 kl=4.3532 lr=4.28e-05 es=0/12

Training:  60%|█████████████████████████████████                      | 60/100 [18:33<12:24, 18.60s/it]

Epoch  60/100 train total=0.1451 recon=0.1231 kl=4.4019 val total=0.1433 recon=0.1214 kl=4.3817 lr=3.52e-05 es=0/12

Training:  65%|███████████████████████████████████▊                   | 65/100 [20:05<10:44, 18.41s/it]

Epoch  65/100 train total=0.1442 recon=0.1223 kl=4.3891 val total=0.1437 recon=0.1217 kl=4.3848 lr=2.80e-05 es=5/12

Training:  70%|██████████████████████████████████████▌                | 70/100 [21:38<09:16, 18.55s/it]

Epoch  70/100 train total=0.1438 recon=0.1217 kl=4.4220 val total=0.1435 recon=0.1217 kl=4.3628 lr=2.14e-05 es=10/12

Training:  75%|█████████████████████████████████████████▎             | 75/100 [23:10<07:42, 18.49s/it]

Epoch  75/100 train total=0.1433 recon=0.1214 kl=4.3664 val total=0.1426 recon=0.1209 kl=4.3323 lr=1.55e-05 es=3/12

Training:  80%|████████████████████████████████████████████           | 80/100 [24:43<06:12, 18.63s/it]

Epoch  80/100 train total=0.1428 recon=0.1207 kl=4.4044 val total=0.1424 recon=0.1207 kl=4.3347 lr=1.05e-05 es=3/12

Training:  85%|██████████████████████████████████████████████▊        | 85/100 [26:16<04:38, 18.56s/it]

Epoch  85/100 train total=0.1423 recon=0.1205 kl=4.3561 val total=0.1423 recon=0.1207 kl=4.3130 lr=6.40e-06 es=1/12

Training:  90%|█████████████████████████████████████████████████▌     | 90/100 [27:49<03:06, 18.65s/it]

Epoch  90/100 train total=0.1424 recon=0.1205 kl=4.3779 val total=0.1424 recon=0.1208 kl=4.3152 lr=3.42e-06 es=6/12

Training:  95%|████████████████████████████████████████████████████▎  | 95/100 [29:22<01:32, 18.55s/it]

Epoch  95/100 train total=0.1423 recon=0.1204 kl=4.3726 val total=0.1423 recon=0.1205 kl=4.3515 lr=1.61e-06 es=4/12

Training: 100%|██████████████████████████████████████████████████████| 100/100 [30:55<00:00, 18.55s/it]

Epoch 100/100 train total=0.1421 recon=0.1202 kl=4.3870 val total=0.1421 recon=0.1202 kl=4.3766 lr=1.00e-06 es=9/12
Best val L1: 0.1413 (epoch=91, ckpt=/home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_006_20260319_031056_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.005/checkpoints/cvae_best.pt)
Loaded checkpoint: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_006_20260319_031056_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.005/checkpoints/cvae_best.pt

Collecting reconstructions:   0%|          | 0/14 [00:00<?, ?it/s]

Griffin-Lim:   0%|          | 0/873 [00:00<?, ?it/s]

  best_val=0.1413
  eval logmel_l1=0.1209 mr_stft=2.1382 si_sdr=-46.77 fad=0.9859
  artifacts -> /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/cvae_nb_006_20260319_031056_lat256_lr0.0001_bs64_st176_nm128_fft2048_hop512_bkl0.005
Completed VAE runs: 5
VAE Summary CSV: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/summary.csv
VAE Summary JSON: /home/kirill/Files/IU_Cources/S26_GenAI/s26_genai_project/experiments/cvae/summary.json

In [ ]:
vae_summary_csv = VAE_EXPERIMENTS_DIR / 'summary.csv'

vae_summary_df = pd.read_csv(vae_summary_csv)
cols = [
    c
    for c in [
        'run_name', 'latent_dim', 'embed_dim', 'base_ch', 'lr', 'batch_size',
        'spec_t', 'n_mels', 'n_fft', 'hop_length', 'beta_kl',
        'best_val', 'logmel_l1', 'mr_stft', 'si_sdr', 'fad',
    ]
    if c in vae_summary_df.columns
]
display(vae_summary_df[cols].sort_values('best_val').reset_index(drop=True))

,run_name,latent_dim,embed_dim,base_ch,lr,batch_size,spec_t,n_mels,n_fft,hop_length,beta_kl,best_val,logmel_l1,mr_stft,si_sdr,fad
0,cvae_nb_005_20260319_023146_lat64_lr0.0003_bs6...,64,32,32,0.0003,64,176,128,2048,512,0.001,0.105789,0.091823,1.897089,-42.203227,3.019801
1,cvae_nb_002_20260319_003524_lat128_lr0.0003_bs...,128,32,32,0.0003,64,176,128,2048,512,0.001,0.105970,0.092518,1.907151,-42.794853,3.337855
2,cvae_nb_003_20260319_011350_lat64_lr0.0001_bs6...,64,32,32,0.0001,64,176,128,2048,512,0.001,0.109498,0.095656,1.928788,-43.421693,3.574586
3,cvae_nb_004_20260319_015341_lat128_lr0.0001_bs...,128,32,32,0.0001,64,176,128,2048,512,0.001,0.111205,0.097182,1.946088,-44.379066,3.894131
4,cvae_nb_006_20260319_031056_lat256_lr0.0001_bs...,256,32,32,0.0001,64,176,128,2048,512,0.005,0.141315,0.120948,2.138150,-46.769296,0.985863